baseURL = 'http://kc13.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
#Paginate = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
pagination.pagerSize = 5
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "Karin Cox | Pitt Neurobiology"  #"Ananke"
weight = 1
contentDir = "content/en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
  name = "CV"
  url = "/docs/cv_kc_260125.pdf"
  weight = 3


[params]
recent_posts_number = 0
show_recent_posts = false
custom_css = ["custom.css"]
summaryLength = 30 # Sets summary to approximately 30 words